version: "3.9"
services:
  discovery:
    build:  ../../discovery-server
    ports:
      - "8761:8761"
    image: "discovery-server"
  fournisseur-ms:
    build: ../../Fournisseur-MS
    environment: 
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
    ports:
      - "8800:8800"
    image: "fournisseur-service"
  facture-ms:
    build: ../../Factures-MS
    environment: 
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
    ports:
      - "8880:8880"
    image: "facture-service"
  categorie-ms:
    build: ../../Categorie_MS
    environment: 
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
    ports:
      - "8801:8801"
    image: "categorie-service"
  livraison-ms:
    build: ../../Livraison-Node-MS
    environment: 
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
    ports:
      - "4401:4401"
    image: "livraison-service"
  config:
    build: ../../config-server
    command: --spring.profiles.active=native --spring.cloud.config.server.native.searchLocations=/config
    volumes:
      - type: bind
        source: ./src/main/resources/centralRepo
        target: /config
    environment: 
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
      - spring.profiles.active=native
    ports:
      - "8888:8888"
    image: "config-server"  
  gateway:
    build: ../../zuul-server
    environment: 
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
    ports:
      - "8762:8762"
    image: "gateway-server"
  